name:                haskevol
version:             0.1.0.0
github:              "https://github.com/rval735/cnn-phd/tree/master/ProjectScope/PP-DNNInHaskell/Evol/haskevol"
license:             BSD3
author:              "rval735"
maintainer:          "rval735"
copyright:           "2018 rval735"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskevol#readme>

dependencies:
- base >= 4.7 && < 5
- MonadRandom >= 0.5
- HUnit >= 1.6
- QuickCheck >= 2.11

library:
  source-dirs: src

executables:
  haskevol-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskevol

tests:
  haskevol-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskevol
