name:                NNClash
version:             "0.1"
github:              "https://github.com/rval735/cnn-phd/tree/master/ProjectScope/PP-DNNInHaskell/NNClash"
license:             GPL-3
author:              "rval735"
maintainer:          "rval735"
copyright:           "2018 rval735"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Simple neural network that analyzes MNIST data in CSV format using Clash to accelerate
# category:            Artificial Intelligence

description:         Please see the README on Github at <https://github.com/rval735/cnn-phd/tree/master/ProjectScope/PP-DNNInHaskell/NNClash#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.1
- time >= 1.8
- bytestring >= 0.1
- clash-ghc >= 0.99
# - constraints >= 0.10
# - void >= 0.7
# - ghc-prim >= 0.5.2
# - newtype-generics >= 0.5.0.1
# - ad >= 4.3.5
# - vector-space >= 0.13
# - constraints >= 0.10
# - categories >= 1.0.7
# - data-category >= 0.7
# - constrained-categories >= 0.3

library:
  source-dirs: src

executables:
  NNClash-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    - -O2
    # - -optc-O2
    # - -fforce-recomp
    # # - -fprof-auto
# Profilers
    # - -fprof-cafs
    # - -fprof-auto
    dependencies:
    - NNClash

tests:
  NNClash-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - NNClash
