name:                "NNHaskell"
version:             0.011
github:              "https://github.com/rval735/cnn-phd/tree/master/ProjectScope/PP-DNNInHaskell/Haskell-Example"
license:             "GPL-3"
author:              "rval735"
maintainer:          "rval735"
copyright:           "2018 rval735"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Simple neural network that analyzes MNIST data in CSV format
# category:            Artificial Intelligence

description:         Please see the README on Github at <https://github.com/rval735/cnn-phd/tree/master/ProjectScope/PP-DNNInHaskell/NNHaskell-Example#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.1
- time >= 1.8
- bytestring >= 0.1
- repa >= 3.4
- mnist-idx >= 0.1.2.8
- vector >= 0.10 && <0.13

library:
  source-dirs: src

executables:
  NNHaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    # - -with-rtsopts=-N
    - -O2
    # - -optc-O2
    # - -fforce-recomp
    # # - -fprof-auto
    # - -Odph
    # - -fno-liberate-case
    # - -funfolding-use-threshold1000
    # - -funfolding-keeness-factor1000
    # - -fllvm
    # - -optlo-O3
# Profilers
    - -fprof-cafs
    - -fprof-auto
    dependencies:
    - NNHaskell

tests:
  NNHaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - NNHaskell
    - QuickCheck >= 2.11.3
    - tasty >= 1.1
    
# Command line
# stack build --profile --executable-profiling --library-profiling
# stack exec NNHaskell-exe -- +RTS -p -h -sstderr
# stack ghci --main-is  NNHaskell:test:NNHaskell-test --test --trace --ghci-options "-fexternal-interpreter -prof"